// Core/SystemAssembly.ts
import './Debug.js';
import '../Window.js';
import '../RenderPhases.js';
import './Object.js';
import '../Ui/Color.js';
import '../Ui/Font.js';
import '../Ui/Panel.js';
import '../Ui/Text.js';
import '../Ui/Scene2D.js';
import '../Controls/Input.js';
import '../Controls/Movement.js';
import '../Controls/Camera.js';
import '../Systems/ImagePasteHandler.js';
import '../Systems/ScriptRunner.js';
import '../Systems/FileMenuActions.js';
import '../Systems/SystemEditor.js';
import '../Assets/Assets.js';
import '../Ui/Objects2D.js';
import '../Ui/SceneTree.js';
import '../Systems/Cursor.js';
import '../Systems/TabSystem.js';
import '../Controls/CloneSystem.js';
// AssetStore will be added when the file is created
